platform :ios, "9.0"

target "almost-secure" do
  use_frameworks!

  # TODO combine frameworks or make them static
  pod "Birdsong", "~> 0.6"
  pod "Result", "~> 4.0"
  pod "KeychainSwift", "~> 12.0"
  pod "GRDBCipher", "~> 3.3"
  # until https://github.com/MessageKit/MessageKit/issues/901
  pod "MessageKit", :git => "git@github.com:MessageKit/MessageKit.git", :branch => "development"
#  pod "SQLCipher", :modular_headers => true
  pod "Reusable", "~> 4.0"
  pod "PromisesSwift", "~> 1.2.3"
#  pod "Hero", "~> 1.3"
  # TODO logger

  target "almost-secureTests" do
    inherit! :search_paths
  end
end
